# Generated by Django 6.1 on 2026-08-15 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_category_at_send', models.CharField(help_text='Risk category at the moment the notification fired (High or Severe)', max_length=20)),
                ('risk_score_at_send', models.FloatField(blank=True, help_text='Risk score at the moment of alert', null=True)),
                ('channel', models.CharField(choices=[('SMS', 'SMS (Twilio)'), ('WhatsApp', 'WhatsApp (Twilio)')], default='SMS', max_length=20)),
                ('recipient', models.CharField(blank=True, help_text='Phone number or WhatsApp target', max_length=50)),
                ('message_body', models.TextField(blank=True, help_text='Alert payload sent via Twilio')),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Failed', 'Failed')], default='Sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='Dispatch timestamp')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='zones.zone')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
