# Generated by Django 6.1 on 2026-08-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='twilio_sid',
            field=models.CharField(blank=True, help_text='Twilio Message SID', max_length=64, null=True),
        ),
    ]
