# Generated by Django 6.1 on 2026-08-15 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_location', models.JSONField(blank=True, help_text='GPS coordinates of the hazard', null=True)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude coordinate', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude coordinate', null=True)),
                ('photo', models.ImageField(blank=True, help_text='Uploaded image of road condition', null=True, upload_to='reports/')),
                ('description', models.TextField(blank=True, help_text='Citizen incident notes or commentary')),
                ('pothole_detected', models.BooleanField(default=False, help_text='True if Hugging Face AI confirms pothole presence')),
                ('pothole_confidence', models.FloatField(default=0.0, help_text='Confidence score of pothole detection model (0.0-1.0)')),
                ('waterlogging_detected', models.BooleanField(default=False, help_text='True if Hugging Face AI confirms waterlogging presence')),
                ('waterlogging_confidence', models.FloatField(default=0.0, help_text='Confidence score of waterlogging detection model (0.0-1.0)')),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', help_text='Administrative review state', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Submission timestamp')),
                ('zone', models.ForeignKey(blank=True, help_text='Auto-assigned zone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='zones.zone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
