# Generated by Django 6.1 on 2026-08-15 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the ward (e.g., Dharampeth, Sitabuldi)', max_length=100, unique=True)),
                ('boundary', models.JSONField(help_text='Spatial boundary polygon outlining the geographic ward area')),
                ('boundary_geojson', models.JSONField(blank=True, help_text='GeoJSON geometry representation for API/Map', null=True)),
                ('elevation_factor', models.FloatField(default=1.0, help_text='Relative elevation indicator (identifies low-lying drainage basins)')),
                ('drainage_capacity', models.FloatField(default=50.0, help_text='Stormwater and sewer runoff capacity rating (0-100)')),
                ('dispatch_status', models.CharField(choices=[('Unassigned', 'Unassigned'), ('Dispatched', 'Dispatched'), ('Resolved', 'Resolved')], default='Unassigned', help_text='Civic response tracking', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rainfall_intensity_mm', models.FloatField(help_text='Rainfall volume in millimeters (mm)')),
                ('source', models.CharField(choices=[('imd_api', 'IMD API / Live Feed'), ('simulated', 'Simulated')], default='simulated', max_length=20)),
                ('recorded_at', models.DateTimeField(help_text='Timestamp when the rainfall measurement was recorded')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_readings', to='zones.zone')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='TrafficReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congestion_level', models.IntegerField(help_text='Traffic index (0 = free-flowing traffic, 100 = gridlock)')),
                ('recorded_at', models.DateTimeField(help_text='Timestamp when the congestion level was recorded')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_readings', to='zones.zone')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
