# Generated by Django 6.1 on 2026-08-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficreading',
            name='current_speed_kmh',
            field=models.FloatField(blank=True, help_text='Current observed road speed (km/h)', null=True),
        ),
        migrations.AddField(
            model_name='trafficreading',
            name='free_flow_speed_kmh',
            field=models.FloatField(blank=True, help_text='Normal free-flow speed (km/h)', null=True),
        ),
        migrations.AddField(
            model_name='trafficreading',
            name='source',
            field=models.CharField(choices=[('tomtom_api', 'TomTom Traffic API'), ('simulated', 'Simulated')], default='simulated', help_text='Data ingestion source', max_length=30),
        ),
    ]
