# Generated by Django 6.1 on 2026-08-15 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Calculated weighted risk index (0-100)')),
                ('category', models.CharField(choices=[('Low', 'Low (0-25)'), ('Medium', 'Medium (26-50)'), ('High', 'High (51-75)'), ('Severe', 'Severe (76-100)')], help_text='Classification level', max_length=20)),
                ('is_photo_confirmed', models.BooleanField(default=False, help_text='Flagged as photo-confirmed if citizen report with waterlogging_detected=True exists')),
                ('computed_at', models.DateTimeField(auto_now_add=True, help_text='Calculation timestamp')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='zones.zone')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
    ]
