# Generated by Django 6.1 on 2026-08-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project or site name (e.g. Wardha Road Metro Corridor)', max_length=200)),
                ('latitude', models.FloatField(help_text='Latitude coordinate')),
                ('longitude', models.FloatField(help_text='Longitude coordinate')),
                ('location', models.JSONField(blank=True, help_text='Geo point of construction site', null=True)),
                ('road_segment_id', models.CharField(blank=True, help_text='Associated road segment ID', max_length=100, null=True)),
                ('source', models.CharField(choices=[('tomtom_incidents_api', 'TomTom Incidents API'), ('manual', 'Manual Admin Entry')], default='manual', help_text='Origin source of the incident/roadwork', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Details of construction or lane restrictions')),
                ('delay_mins', models.FloatField(default=3.0, help_text='Estimated traffic delay in minutes')),
                ('active', models.BooleanField(default=True, help_text='Whether this roadwork project is actively disrupting flow')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when construction zone was added')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
